---
abstract: 'Access the JSON-RPC API of a Zabbix server'
author:
  - 'Fabrice Gabolde <fabrice.gabolde@uperto.com>'
  - 'Marc Dequenes <marc.dequenes@uperto.com>'
build_requires:
  File::Spec: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36_14
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Zabbix-API
provides:
  Zabbix::API:
    file: lib/Zabbix/API.pm
    version: 0.004
  Zabbix::API::Action:
    file: lib/Zabbix/API/Action.pm
    version: 0
  Zabbix::API::CRUDE:
    file: lib/Zabbix/API/CRUDE.pm
    version: 0
  Zabbix::API::Graph:
    file: lib/Zabbix/API/Graph.pm
    version: 0
  Zabbix::API::Host:
    file: lib/Zabbix/API/Host.pm
    version: 0
  Zabbix::API::HostGroup:
    file: lib/Zabbix/API/HostGroup.pm
    version: 0
  Zabbix::API::Item:
    file: lib/Zabbix/API/Item.pm
    version: 0
  Zabbix::API::Macro:
    file: lib/Zabbix/API/Macro.pm
    version: 0
  Zabbix::API::Map:
    file: lib/Zabbix/API/Map.pm
    version: 0
  Zabbix::API::Screen:
    file: lib/Zabbix/API/Screen.pm
    version: 0
  Zabbix::API::Trigger:
    file: lib/Zabbix/API/Trigger.pm
    version: 0
  Zabbix::API::Utils:
    file: lib/Zabbix/API/Utils.pm
    version: 0
requires:
  JSON: 0
  LWP: 0
  Params::Validate: 0
  perl: 5.010001
resources:
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: git://github.com/SFR-ZABBIX/Zabbix-API.git
version: 0.004
